name: py-winrm-plugin
rundeckPluginVersion: 2.0
author: "@author@"
date: "@date@"
version: "@version@"
url: "@url@"
description: "Python WINRM node executor and file copier"
rundeckCompatibilityVersion: "3.x"
targetHostCompatibility: "all"
license: "Apache 2.0"
tags:
    - script
    - NodeExecutor
    - FileCopier
providers:
  - name: WinRMPython
    title: WinRM Node Executor Python
    description: Executing Scripts or Commands on remote Windows computer
    service: NodeExecutor
    plugin-type: script
    script-interpreter: ${config.interpreter} -u
    script-file: winrm-exec.py
    script-args: ${node.hostname}
    config:
      - name: interpreter
        title: Python Interpreter
        description: "Python Interpreter (Default: python)"
        type: String
        default: "python"
        required: true
        scope: Instance
      - name: authtype
        title: Authentication Type
        description: "Authentication Type. It can be overwriting at node level using `winrm-authtype`"
        type: Select
        values: "basic,credssp,ntlm,kerberos"
        default: "basic"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Authentication
          instance-scope-node-attribute: "winrm-authtype"
      - name: nossl
        title: No SSL Verification
        description: "When set to true ssl certificate validation is not performed. It can be overwriting at node level using `winrm-nossl`"
        type: Select
        values: "true, false"
        default: "false"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-nossl"
      - name: disabletls12
        title: Disable TLS 1.2
        description: "Disable TLS 1.2 in order to run over TLS 1.0"
        type: Boolean
        default: "false"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-disable-tls-12"
      - name: winrmtransport
        title: WinRM Transport Protocol
        description: "WinRM transport protocol (http or https). It can be overwriting at node level using `winrm-transport`"
        type: Select
        default: "http"
        values: "http, https"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-transport"
      - name: winrmport
        title: WinRM Port
        description: "WinRM port (Default: 5985/5986 for http/https). It can be overwriting at node level using `winrm-port`"
        type: String
        default: "5985"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-port"
      - name: certpath
        title: Certificate Path
        description: "Certificate path for ssl verification. It can be overwriting at node level using `winrm-certpath`"
        type: String
        required: false
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-certpath"
      - name: readtimeout
        title: connect/read times out
        description: "maximum seconds to wait before an HTTP connect/read times out (default 30). This value should be slightly higher than operation timeout, as the server can block *at least* that long. It can be overwriting at node level using `winrm-readtimeout`"
        type: String
        required: false
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-readtimeout"
      - name: operationtimeout
        title: operation timeout
        description: "maximum allowed time in seconds for any single wsman HTTP operation (default 20). Note that operation timeouts while receiving output (the only wsman operation that should take any significant time, and where these timeouts are expected) will be silently retried indefinitely. It can be overwriting at node level using `winrm-operationtimeout`"
        type: String
        required: false
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-operationtimeout"
      - name: shell
        title: Shell
        description: "Windows Shell interpreter. It can be overwriting at node level using `winrm-shell`"
        type: Select
        values: "cmd, powershell"
        default: 'powershell'
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-shell"
      - name: exitbehaviour
        title: Script Exit Behaviour
        description: "Script Exit Behaviour. console: if the std error console has data (default), the process fails. exitcode: script won't fail by default, the user must control the exit code (eg: using try/catch block). See https://github.com/rundeck-plugins/py-winrm-plugin/tree/master#running-scripts"
        type: Select
        values: "console, exitcode"
        default: "console"
        required: true
        renderingOptions:
          groupName: Connection
      - name: username
        title: Username
        type: String
        required: false
        description: "Optional username. The username can be set at node level (using the attribute `username`) or at job level (using an input option called `username`)."
        scope: Instance
        renderingOptions:
          groupName: Authentication
      - name: password_storage_path
        title: Password Storage Path
        type: String
        required: false
        description: "Optional storage password path. Can contain property references to node attributes. A node attribute named winrm-password-storage-path will override this value. Also, it can be set at job level using the option name `winrmpassword`"
        scope: Instance
        renderingOptions:
          groupName: Authentication
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
          instance-scope-node-attribute: "winrm-password-storage-path"
      - name: krb5config
        title: krb5 Config File
        description: "Path of krb5.conf file"
        type: String
        default: '/etc/krb5.conf'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: kinit
        title: Kinit Command
        description: "Kinit Command"
        type: String
        default: 'kinit'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: krbdelegation
        title: Kerberos Delegations
        description: "Kerberos Delegation: if True, TGT is sent to target server to allow multiple hops"
        type: Boolean
        default: "false"
        required: false
        renderingOptions:
          groupName: Kerberos
  - name: WinRMcpPython
    title: WinRM Python File Copier
    description: Copying files to remote Windows computer
    service: FileCopier
    plugin-type: script
    script-interpreter: ${config.interpreter} -u
    script-file: winrm-filecopier.py
    script-args: ${node.hostname} ${file-copy.file} ${file-copy.destination}
    config:
      - name: interpreter
        title: Python Interpreter
        description: "Python Interpreter (Default: python)"
        type: String
        default: "python"
        required: true
        scope: Instance
      - name: authtype
        title: Authentication Type
        description: "Authentication Type. It can be overwriting at node level using `winrm-authtype`"
        type: Select
        values: "basic,credssp,ntlm,kerberos"
        default: "basic"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Authentication
          instance-scope-node-attribute: "winrm-authtype"
      - name: nossl
        title: No SSL Verification
        description: "When set to true ssl certificate validation is not performed. It can be overwriting at node level using `winrm-nossl`"
        type: Select
        values: "true, false"
        default: "false"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-nossl"
      - name: disabletls12
        title: Disable TLS 1.2
        description: "Disable TLS 1.2 in order to run over TLS 1.0"
        type: Boolean
        default: "false"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-disable-tls-12"
      - name: winrmtransport
        title: WinRM Transport Protocol
        description: "WinRM transport protocol (Default: http or https when ssl is selected for Authentication type). It can be overwriting at node level using `winrm-transport`"
        type: Select
        default: "http"
        values: "http, https"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-transport"
      - name: winrmport
        title: WinRM Port
        description: "WinRM port (Default: 5985/5986 for http/https). It can be overwriting at node level using `winrm-port`"
        type: String
        default: "5985"
        required: true
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-port"
      - name: certpath
        title: Certificate Path
        description: "Certificate path for ssl verification. It can be overwriting at node level using `winrm-certpath`"
        type: String
        required: false
        scope: Instance
        renderingOptions:
          groupName: Connection
          instance-scope-node-attribute: "winrm-certpath"
      - name: username
        title: Username
        type: String
        required: false
        description: "Optional username. The username can be set at node level (using the attribute `username`) or at job level (using an input option called `username`)."
        scope: Instance
        renderingOptions:
          groupName: Authentication
      - name: password_storage_path
        title: Password Storage Path
        type: String
        required: false
        description: "Optional storage password path. Can contain property references to node attributes. A node attribute named winrm-password-storage-path will override this value. Also, it can be set at job level using the option name `winrmpassword`"
        scope: Instance
        renderingOptions:
          groupName: Authentication
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
          instance-scope-node-attribute: "winrm-password-storage-path"
      - type: Boolean
        name: debug
        title: Debug?
        description: 'Write debug messages'
      - name: krb5config
        title: krb5 Config File
        description: "Path of krb5.conf file"
        type: String
        default: '/etc/krb5.conf'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: kinit
        title: Kinit Command
        description: "Kinit Command"
        type: String
        default: 'kinit'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: krbdelegation
        title: Kerberos Delegations
        description: "Kerberos Delegation: if True, TGT is sent to target server to allow multiple hops"
        type: Boolean
        default: "false"
        required: false
        renderingOptions:
          groupName: Kerberos
  - name: WinRMCheck
    title: WinRM Check Step
    description: Check the connection with a remote node using winrm-python
    service: WorkflowStep
    plugin-type: script
    script-interpreter: ${config.interpreter} -u
    script-file: winrm-check.py
    script-args: --username ${config.username} --hostname ${config.hostname} --password ${config.password_storage_path} --authentication ${config.authtype} --transport ${config.winrmtransport} --port ${config.winrmport} --nossl ${config.nossl} --debug ${config.debug} --certpath ${config.certpath}
    config:
      - name: interpreter
        title: Python Interpreter
        description: "Python Interpreter (Default: python)"
        type: String
        default: "python"
        required: true
        scope: Instance
      - name: hostname
        title: Hostname
        description: "Window's Hostname"
        type: String
        required: true
      - name: authtype
        title: Authentication Type
        description: "Authentication Type"
        type: Select
        values: "basic,credssp,ntlm,kerberos"
        default: "basic"
        required: true
      - name: winrmtransport
        title: WinRM Transport Protocol
        description: "WinRM transport protocol (http or https)"
        type: Select
        default: "http"
        values: "http, https"
        required: true
        scope: Instance
      - name: nossl
        title: No SSL Verification
        description: "When set to true ssl certificate validation is not performed"
        type: Select
        values: "true, false"
        default: "false"
        required: true
      - name: disabletls12
        title: Disable TLS 1.2
        description: "Disable TLS 1.2 in order to run over TLS 1.0"
        type: Boolean
        default: "false"
        required: true
      - name: winrmport
        title: WinRM Port
        description: "WinRM port (Default: 5985/5986 for http/https)"
        type: String
        default: "5985"
        required: true
      - name: certpath
        title: Certificate Path
        description: "Certificate path for ssl verification"
        type: String
        required: false
      - name: username
        title: Username
        description: "Username from window box"
        type: String
        required: true
      - name: password_storage_path
        title: Password Storage Path
        type: String
        required: true
        description: "Password storage password path."
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
      - type: Boolean
        name: debug
        title: Debug?
        description: 'Write debug messages'
      - name: krb5config
        title: krb5 Config File
        description: "Path of krb5.conf file"
        type: String
        default: '/etc/krb5.conf'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: kinit
        title: Kinit Command
        description: "Kinit Command"
        type: String
        default: 'kinit'
        required: false
        renderingOptions:
          groupName: Kerberos
      - name: krbdelegation
        title: Kerberos Delegations
        description: "Kerberos Delegation: if True, TGT is sent to target server to allow multiple hops"
        type: Boolean
        default: "false"
        required: false
        renderingOptions:
          groupName: Kerberos

